import type { ResearchEntry } from "./research";

export const delphiResearch: ResearchEntry[] = [
  { id: "delphi-monte-carlo", method: "Monte Carlo pricing", title: "Options: A Monte Carlo Approach", authors: "Phelim P. Boyle", year: "1977", source: "https://doi.org/10.1016/0304-405X(77)90005-8", access: "Publisher · access may vary", tools: ["Delphi"],
    summary: "Values options by simulating risk-neutral asset returns and averaging discounted payoffs, with techniques to improve simulation efficiency.",
    implementation: "Delphi generates its high-fidelity reference from seeded risk-neutral GBM simulations. Antithetic pairs reduce sampling variance, and shared random draws support surface comparisons. Monte Carlo standard errors measure sampling uncertainty; the reference is not exact truth." },
  { id: "delphi-splines", method: "Tensor interpolation", title: "RegularGridInterpolator", authors: "SciPy contributors", year: "Living documentation", source: "https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RegularGridInterpolator.html", access: "Open documentation", tools: ["Delphi"],
    summary: "Interpolates observations arranged on a rectangular grid, including tensor-product cubic splines.",
    implementation: "Delphi uses cubic interpolation on normalized spot and maturity coordinates. Every method receives the same tensor knots. Extrapolation extends the fitted spline and can violate option-price bounds; predictions remain visible with diagnostics." },
  { id: "delphi-gaussian-process", method: "Probabilistic regression", title: "Gaussian Processes for Machine Learning", authors: "Carl Edward Rasmussen & Christopher K. I. Williams", year: "2006", source: "https://gaussianprocess.org/gpml/", access: "Author-hosted book", tools: ["Delphi"],
    summary: "A treatment of regression using covariance functions and conditional Gaussian distributions.",
    implementation: "Delphi uses an exact Gaussian process with a fixed RBF kernel, training-only normalization, Monte Carlo standard errors on the diagonal, a noise floor, and bounded numerical jitter. Latent posterior standard deviation describes the fitted GP. It is neither a pricing-error guarantee nor Monte Carlo standard error; correlated reference noise is approximated diagonally." },
  { id: "delphi-neural-approximation", method: "Neural approximation", title: "Multilayer Feedforward Networks Are Universal Approximators", authors: "Kurt Hornik, Maxwell Stinchcombe & Halbert White", year: "1989", source: "https://doi.org/10.1016/0893-6080(89)90020-8", access: "Publisher · access may vary", tools: ["Delphi"],
    summary: "Establishes the approximation capacity of feedforward neural networks with suitable activation functions and sufficiently many hidden units.",
    implementation: "Delphi's direct MLP uses two tanh hidden layers to learn the reference surface from shared training knots. Training uses full-batch Adam, squared error, and weight regularization. Universal approximation motivates the model class; it does not guarantee that this finite network or fixed training budget achieves a desired accuracy." },
  { id: "delphi-residual-learning", method: "Multi-fidelity / residual learning", title: "SABR Equipped with AI Wings", authors: "Hideharu Funahashi", year: "2023 · online 2022", source: "https://doi.org/10.1080/14697688.2022.2150561", access: "Publisher · access may vary", tools: ["Delphi"],
    summary: "Uses neural networks to learn corrections between asymptotic implied-volatility approximations and Monte Carlo results under SABR models.",
    implementation: "This provides finance-specific context for learning a residual around an analytical baseline. Delphi adds an MLP correction to Black–Scholes using the same architecture, seed, and epoch budget as the direct MLP. Delphi currently uses constant-volatility GBM, not SABR: Black–Scholes is its analytical expectation, so the correction primarily fits Monte Carlo sampling error." },
  { id: "delphi-surrogate-modeling", method: "Surrogate modeling", title: "Bayesian Calibration of Computer Models", authors: "Marc C. Kennedy & Anthony O’Hagan", year: "2001", source: "https://doi.org/10.1111/1467-9868.00294", access: "Publisher · access may vary", tools: ["Delphi"],
    summary: "Develops Bayesian calibration of computer models with uncertainty about fitted parameters and a discrepancy term for model inadequacy.",
    implementation: "This supplies broader context for surrogate prediction and model discrepancy when comparing approximations with a reference. Delphi measures surrogate error against a simulated reference and displays GP uncertainty. It does not implement the paper's Bayesian calibration procedure or infer model discrepancy from observed market data." },
];
